
package com.fabiorapanelo.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderManagement", targetNamespace = "http://order.fabiorapanelo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderManagement {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkStatus", targetNamespace = "http://order.fabiorapanelo.com/", className = "com.fabiorapanelo.order.CheckStatus")
    @ResponseWrapper(localName = "checkStatusResponse", targetNamespace = "http://order.fabiorapanelo.com/", className = "com.fabiorapanelo.order.CheckStatusResponse")
    @Action(input = "http://order.fabiorapanelo.com/OrderManagement/checkStatusRequest", output = "http://order.fabiorapanelo.com/OrderManagement/checkStatusResponse")
    public String checkStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
